export const ROUTES = {
	HOME: "/",
	CLUB_NEW: "/club/new",
	CLUB_DASHBOARD: (id: string) => `/club/${id}`,
	CLUB_HISTORY: (id: string) => `/club/${id}/history`,
	CLUB_SETTINGS: (id: string) => `/club/${id}/settings`,
	CLUB_SELECT: (id: string) => `/club/${id}/select`,
	API_BOOKS_SEARCH: "/api/books/search",
	API_CLUB_CREATE: "/api/club/create",
	API_CLUB_JOIN: "/api/club/join",
	API_CLUB_PDF: (id: string) => `/api/club/${id}/pdf`,
	API_CLUB_PROGRESS: (id: string) => `/api/club/${id}/progress`,
	API_CLUB_CADENCE: (id: string) => `/api/club/${id}/cadence`,
	API_CRON_PURGE: "/api/cron/purge",
} as const;
